package ingest

// jsUpperCaseSpecials is every BMP code point whose JavaScript toUpperCase differs from
// Go's strings.ToUpper: the full Unicode case mapping against the simple one (U+00DF → "SS"),
// plus a handful of code points where the two runtimes ship different Unicode versions.
//
// Generated by running both runtimes over U+0000–U+FFFF and keeping the disagreements. Only
// jsUpperFirst reads it, and only for the first character of a note title.
var jsUpperCaseSpecials = map[rune]string{
	0x00DF: "SS",  // U+0053 U+0053
	0x0149: "ʼN",  // U+02BC U+004E
	0x019B: "Ƛ",   // U+A7DC
	0x01F0: "J̌",  // U+004A U+030C
	0x0264: "Ɤ",   // U+A7CB
	0x0390: "Ϊ́", // U+0399 U+0308 U+0301
	0x03B0: "Ϋ́", // U+03A5 U+0308 U+0301
	0x0587: "ԵՒ",  // U+0535 U+0552
	0x1C8A: "Ᲊ",   // U+1C89
	0x1E96: "H̱",  // U+0048 U+0331
	0x1E97: "T̈",  // U+0054 U+0308
	0x1E98: "W̊",  // U+0057 U+030A
	0x1E99: "Y̊",  // U+0059 U+030A
	0x1E9A: "Aʾ",  // U+0041 U+02BE
	0x1F50: "Υ̓",  // U+03A5 U+0313
	0x1F52: "Υ̓̀", // U+03A5 U+0313 U+0300
	0x1F54: "Υ̓́", // U+03A5 U+0313 U+0301
	0x1F56: "Υ̓͂", // U+03A5 U+0313 U+0342
	0x1F80: "ἈΙ",  // U+1F08 U+0399
	0x1F81: "ἉΙ",  // U+1F09 U+0399
	0x1F82: "ἊΙ",  // U+1F0A U+0399
	0x1F83: "ἋΙ",  // U+1F0B U+0399
	0x1F84: "ἌΙ",  // U+1F0C U+0399
	0x1F85: "ἍΙ",  // U+1F0D U+0399
	0x1F86: "ἎΙ",  // U+1F0E U+0399
	0x1F87: "ἏΙ",  // U+1F0F U+0399
	0x1F88: "ἈΙ",  // U+1F08 U+0399
	0x1F89: "ἉΙ",  // U+1F09 U+0399
	0x1F8A: "ἊΙ",  // U+1F0A U+0399
	0x1F8B: "ἋΙ",  // U+1F0B U+0399
	0x1F8C: "ἌΙ",  // U+1F0C U+0399
	0x1F8D: "ἍΙ",  // U+1F0D U+0399
	0x1F8E: "ἎΙ",  // U+1F0E U+0399
	0x1F8F: "ἏΙ",  // U+1F0F U+0399
	0x1F90: "ἨΙ",  // U+1F28 U+0399
	0x1F91: "ἩΙ",  // U+1F29 U+0399
	0x1F92: "ἪΙ",  // U+1F2A U+0399
	0x1F93: "ἫΙ",  // U+1F2B U+0399
	0x1F94: "ἬΙ",  // U+1F2C U+0399
	0x1F95: "ἭΙ",  // U+1F2D U+0399
	0x1F96: "ἮΙ",  // U+1F2E U+0399
	0x1F97: "ἯΙ",  // U+1F2F U+0399
	0x1F98: "ἨΙ",  // U+1F28 U+0399
	0x1F99: "ἩΙ",  // U+1F29 U+0399
	0x1F9A: "ἪΙ",  // U+1F2A U+0399
	0x1F9B: "ἫΙ",  // U+1F2B U+0399
	0x1F9C: "ἬΙ",  // U+1F2C U+0399
	0x1F9D: "ἭΙ",  // U+1F2D U+0399
	0x1F9E: "ἮΙ",  // U+1F2E U+0399
	0x1F9F: "ἯΙ",  // U+1F2F U+0399
	0x1FA0: "ὨΙ",  // U+1F68 U+0399
	0x1FA1: "ὩΙ",  // U+1F69 U+0399
	0x1FA2: "ὪΙ",  // U+1F6A U+0399
	0x1FA3: "ὫΙ",  // U+1F6B U+0399
	0x1FA4: "ὬΙ",  // U+1F6C U+0399
	0x1FA5: "ὭΙ",  // U+1F6D U+0399
	0x1FA6: "ὮΙ",  // U+1F6E U+0399
	0x1FA7: "ὯΙ",  // U+1F6F U+0399
	0x1FA8: "ὨΙ",  // U+1F68 U+0399
	0x1FA9: "ὩΙ",  // U+1F69 U+0399
	0x1FAA: "ὪΙ",  // U+1F6A U+0399
	0x1FAB: "ὫΙ",  // U+1F6B U+0399
	0x1FAC: "ὬΙ",  // U+1F6C U+0399
	0x1FAD: "ὭΙ",  // U+1F6D U+0399
	0x1FAE: "ὮΙ",  // U+1F6E U+0399
	0x1FAF: "ὯΙ",  // U+1F6F U+0399
	0x1FB2: "ᾺΙ",  // U+1FBA U+0399
	0x1FB3: "ΑΙ",  // U+0391 U+0399
	0x1FB4: "ΆΙ",  // U+0386 U+0399
	0x1FB6: "Α͂",  // U+0391 U+0342
	0x1FB7: "Α͂Ι", // U+0391 U+0342 U+0399
	0x1FBC: "ΑΙ",  // U+0391 U+0399
	0x1FC2: "ῊΙ",  // U+1FCA U+0399
	0x1FC3: "ΗΙ",  // U+0397 U+0399
	0x1FC4: "ΉΙ",  // U+0389 U+0399
	0x1FC6: "Η͂",  // U+0397 U+0342
	0x1FC7: "Η͂Ι", // U+0397 U+0342 U+0399
	0x1FCC: "ΗΙ",  // U+0397 U+0399
	0x1FD2: "Ϊ̀", // U+0399 U+0308 U+0300
	0x1FD3: "Ϊ́", // U+0399 U+0308 U+0301
	0x1FD6: "Ι͂",  // U+0399 U+0342
	0x1FD7: "Ϊ͂", // U+0399 U+0308 U+0342
	0x1FE2: "Ϋ̀", // U+03A5 U+0308 U+0300
	0x1FE3: "Ϋ́", // U+03A5 U+0308 U+0301
	0x1FE4: "Ρ̓",  // U+03A1 U+0313
	0x1FE6: "Υ͂",  // U+03A5 U+0342
	0x1FE7: "Ϋ͂", // U+03A5 U+0308 U+0342
	0x1FF2: "ῺΙ",  // U+1FFA U+0399
	0x1FF3: "ΩΙ",  // U+03A9 U+0399
	0x1FF4: "ΏΙ",  // U+038F U+0399
	0x1FF6: "Ω͂",  // U+03A9 U+0342
	0x1FF7: "Ω͂Ι", // U+03A9 U+0342 U+0399
	0x1FFC: "ΩΙ",  // U+03A9 U+0399
	0xA7CD: "Ꟍ",   // U+A7CC
	0xA7DB: "Ꟛ",   // U+A7DA
	0xFB00: "FF",  // U+0046 U+0046
	0xFB01: "FI",  // U+0046 U+0049
	0xFB02: "FL",  // U+0046 U+004C
	0xFB03: "FFI", // U+0046 U+0046 U+0049
	0xFB04: "FFL", // U+0046 U+0046 U+004C
	0xFB05: "ST",  // U+0053 U+0054
	0xFB06: "ST",  // U+0053 U+0054
	0xFB13: "ՄՆ",  // U+0544 U+0546
	0xFB14: "ՄԵ",  // U+0544 U+0535
	0xFB15: "ՄԻ",  // U+0544 U+053B
	0xFB16: "ՎՆ",  // U+054E U+0546
	0xFB17: "ՄԽ",  // U+0544 U+053D
}
